// SEO configuration for bey-library (English)
export const seo = {
  title: "Beyblade X Library - The Ultimate Beyblade X Parts Catalog",
  description: "Discover, compare, and learn about Beyblade X parts. Find blades, bits, and accessories with detailed information and images. Perfect for Beyblade X collectors and enthusiasts!",
  keywords: [
    "Beyblade X",
    "Beyblade X database",
    "Beyblade X Library",
    "Beyblade X parts database",
    "Beyblade X component list",
    "Beyblade X parts catalog",
    "Beyblade X parts info",
    "Beyblade X blades list",
    "Beyblade X ratchet list",
    "Beyblade X bits list",
    "Beyblade X accessory database",
    "Beyblade X compatible parts",
    "Beyblade X customization guide",
    "Beyblade X part names",
    "Beyblade X unique parts",
    "Beyblade X rare parts",
    "Beyblade X exclusive components",
    "Beyblade X performance parts",
    "Beyblade X part details",
    "Beyblade X part specifications",
    "Beyblade X part numbers",
    "Beyblade X breakdown",
    "Beyblade X technical data",
    "Beyblade X interchangeable parts",
    "Beyblade X build guide",
    "Beyblade X complete parts list",
    "Beyblade X part descriptions",
    "Beyblade X part functions",
    "Beyblade X part types",
    "Beyblade X generations parts",
    "Beyblade X official parts",
    "Beyblade X stock parts",
    "Beyblade X custom parts",
    "Beyblade X analysis parts",
    "Beyblade X component breakdown",
    "Beyblade X material info",
    "Beyblade X weight info",
    "Beyblade X part dimensions",
    "Beyblade X battle strategies",
    "Beyblade X tournament tips",
    "Beyblade X best builds",
    "Beyblade X combo guide",
    "Beyblade X competitive parts",
    "Beyblade X spin techniques",
    "Beyblade X launcher guide",
    "Beyblade X stadium guide",
    "Beyblade X new releases",
    "Beyblade X limited edition",
    "Beyblade X collector’s guide",
    "Beyblade X model comparison",
    "Beyblade X reviews",
    "Beyblade X gameplay tips",
    "Beyblade X custom combos",
    "Beyblade X part upgrades",
    "Beyblade X official tournaments",
    "Beyblade X community builds",
    "Beyblade X part compatibility chart",
    "Beyblade X balance type parts",
    "Beyblade X attack type parts",
    "Beyblade X defense type parts",
    "Beyblade X stamina type parts",
    "Beyblade X rare blades",
    "Beyblade X exclusive ratchets",
    "Beyblade X performance bits",
    "Beyblade X battle arena",
    "Beyblade X starter packs",
    "Beyblade X accessories list"
  ],
  openGraph: {
    title: "Beyblade X Library - The Ultimate Beyblade X Parts Catalog",
    description: "Explore the most comprehensive Beyblade X parts database. Find everything you need to know about Beyblade X blades, bits, and more!",
    url: "https://bey-library.vercel.app/",
    type: "website",
    images: [
      {
        url: "/favicon.png",
        width: 512,
        height: 512,
        alt: "Beyblade X Library Logo"
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    title: "Beyblade X Library - The Ultimate Beyblade X Parts Catalog",
    description: "Discover, compare, and learn about Beyblade X parts. Perfect for Beyblade X collectors and enthusiasts!",
    image: "/favicon.png"
  }
};

export default seo;
